### PR TITLE
Add RazorSlice finalizer

### PR DESCRIPTION
**Pull request by sebastienros**
Return pooled objects during finalization when Dispose is not invoked.

### CODE REVIEW

**Review by DamianEdwards — APPROVED** [review]
Thanks!

**Comment by davidfowl** [comment]
Why?

**Comment by sebastienros** [comment]
Return pooled objects during finalization when Dispose is not invoked.

Why not?

**Comment by sebastienros** [comment]
A reason I could see for not doing it is that it might be useless, meaning when the finalizer is invoked then the cached instance which is a threadstatic instance, not an actual pool, would probably already be replaced so we don't save anything, or that several other instances wouldn't be disposed and it would also not be useful. But is it a bad practice to return it in the finalizer or not beneficial in that case.

**Comment by davidfowl** [comment]
Because we have a GC and unlike a pool in native code, the downside is that the object gets garbage collected. This is only worth doing if there's a real big downside to not returning.

**Comment by sebastienros** [comment]
I see. What may have been the point of this code (before the PR) if there was no explicit finalizer?

```c#
public virtual void Dispose()
{
...
    ReturnPooledObjects();
    GC.SuppressFinalize(this);
}
```

**Pull request merged**
